mutation updateMoneyByUserId($id: uuid!, $newAmount: money!) {
  update_Money(where: { userId: { _eq: $id } }, _set: { amount: $newAmount }) {
    affected_rows
  }
}

mutation insertUserByEmail($email: String!) {
  insert_User_one(object: { email: $email }) {
    id
    email
  }
}
