query getAll {
  Opportunity {
    name
    Address {
      city
      country
      id
      state
      streetAddress
      zipCode
    }
    OpportunityVolunteers {
      Volunteer {
        name
      }
    }
  }
}
